name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build deps
      run: |
        make deps
    - name: Build
      run: |
        make -j2
